<project name="freeplane_mac" default="dist" basedir="..">
	<property name="workspace" location=".." />
	<property name="src" value="src" />
	<property file="${workspace}/freeplane_framework/ant/ant.properties" />
	<property file="${workspace}/freeplane/ant/ant.properties" />
	<property name="build" value="build" />
	<property name="dist" value="dist" />
	<property name="debug" value="on" />
	<property name="java_source_version" value="1.8" />
	<property name="java_target_version" value="1.8" />
	<property name="build.compiler" value="modern" />
	<property name="classpath" value="${framework.jar}:${freeplane.jars}"/>

	<target name="build">
		<echo>freeplanemac.jar already exists, skipping compilation</echo>
	</target>


	<target name="dist" depends="build">
		<echo>Using existing freeplanemac.jar in ${workspace}/freeplane/lib/</echo>
	</target>

	<target name="clean">
		<delete dir="${build}"  quiet="true"/>
		<delete>
			<fileset defaultexcludes="no" dir="${src}" includes="**/*~"/>
		</delete>
	</target>
	
</project>

