swingworker.jar = ${workspace}/docear_plugin_core/dist/org.docear.plugin.core/lib/swingworker-backport.jar
core.jar = ${workspace}/docear_plugin_core/dist/org.docear.plugin.core/lib/plugin.jar
jgoodies.jar = ${workspace}/freeplane/dist/org.freeplane.core/lib/forms-1.2.1.jar
